### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by cp2004** [TheLongRunSmoke/OctoPrint-Filetypes#1]
Hi there! I don't use this plugin, but have been helping out with getting OctoPrint to Python 3.
As you are probably aware, OctoPrint currently supports Python 2 & 3 simultaneously. Users will begin migrating to Python 3 soon and your plugin will not be installable for them. As of March 2021, it will switch to Python 3 only.
Please see the guide [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html)

Having taken a look at your plugin, all it probably needs is to add the compatibility flag, as mentioned in the above link. I'd be happy to do it and update the plugin repo for you, if you will accept a pull request.

**Comment by TheLongRunSmoke** [comment]
Hi. I wrote this plugin are years ago. It's incompatible with modern OctoPrint in various ways and must be rewrited completely.
